version: '3.3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongodbservice
    network_mode: host
  eurekaServer:
    image: eureka-server
    build:
      context: EurekaServer
    restart: "no"
    environment:
      EUREKA_SERVER_PORT: 8761
    ports:
      - 8761:8761
  cloudapiservice:
    image: api-gateway-service
    build:
      context: APIGateway
    restart: "no"
    ports:
      - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eurekaServer
  adminservice:
    container_name: admin-service
    network_mode: host
    build:
      context: Admin
    hostname: localhost
    ports:
      - 8000:8000
    restart: "no"
    depends_on:
      - mongo
      - eurekaServer
      - cloudapiservice
  bookingservice:
    container_name: booking-service
    build:
      context: BookingService
    hostname: localhost
    ports:
      - 8082:8082
    restart: "no"
    depends_on:
      - mongo
      - eurekaServer
      - cloudapiservice
  emailservice:
    container_name: email-service
    build:
      context: EmailService
    hostname: localhost
    ports:
      - 8081:8081
    restart: "no"
    depends_on:
      - mongo
      - eurekaServer
      - cloudapiservice
  hotelservice:
    container_name: hotel-service
    build:
      context: Hotels
    hostname: localhost
    ports:
      - 8087:8087
    restart: "no"
    depends_on:
      - mongo
      - eurekaServer
      - cloudapiservice
  ownerservice:
    container_name: owner-service
    build:
      context: Owner
    hostname: localhost
    ports:
      - 8083:8083
    restart: "no"
    depends_on:
      - mongo
      - eurekaServer
      - cloudapiservice
  registerservice:
    container_name: register-service
    network_mode: host
    build:
      context: RegistrationService
    hostname: localhost
    ports:
      - 8088:8088
    restart: "no"
    depends_on:
      - mongo
      - eurekaServer
      - cloudapiservice
