server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/MakeMyYatraa
  application:
    name: email-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id:  my-group
      value-serializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
  mail:
    host: smtp.gmail.com
    port: 587
    username: AllInOneApp00@gmail.com
    password: danqnjdbeapfgosv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true