server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/MakeMyYatraa
  application:
    name: booking-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
vonage:
  api-key: 79e24189
  api-secret: 6miUDJMpLlwlVCTV
  phone-number: +918380993390