server:
  port: 8083
spring:
  data:
    mongodb:
#      uri: mongodb://mongo:27017/MakeMyYatraa
      uri: mongodb://localhost:27017/MakeMyYatraa
  application:
    name: owner-service
eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true