server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MakeMyYatraa?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: login-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true